In [1]:
import numpy as np

In [160]:
encmat = '5 3 0;4 3 -1;5 2 2'            ## each row separated by semicolon
msg = "DR JOHN IS THE SPY".lower()


mat = np.matrix(encmat)
ncr = mat.shape[0]

cors = {}
cors[" "] = 0
for x in range(1,27):
    cors[chr(96+x)] = x

nrr = len(msg)/ncr
nrr = np.ceil(nrr)
mmsg = [cors[x] for x in msg]
while(len(mmsg) < ncr*nrr):
    mmsg.append(0)

lol = []
for x in range(0,len(mmsg),ncr):
    lol.append(mmsg[x:x+ncr])

lol = np.matrix(lol)
enc = lol * mat


In [161]:
### Message in Numbers
print(lol)

[[ 4 18  0]
 [10 15  8]
 [14  0  9]
 [19  0 20]
 [ 8  5  0]
 [19 16 25]]


In [162]:
### Encrypted Message
print(enc)

[[ 92  66 -18]
 [150  91   1]
 [115  60  18]
 [195  97  40]
 [ 60  39  -5]
 [284 155  34]]


In [163]:
## Encryption Key Adjoint Matrix (used for calculating inverse)
np.linalg.det(mat)*np.linalg.inv(mat)

matrix([[  8.,  -6.,  -3.],
        [-13.,  10.,   5.],
        [ -7.,   5.,   3.]])

In [164]:
## Inverse of Encryption Matrix (Decryption Matrix)
np.linalg.inv(mat)

matrix([[  8.,  -6.,  -3.],
        [-13.,  10.,   5.],
        [ -7.,   5.,   3.]])

In [172]:
##Pointless verification 
enc*np.linalg.inv(mat).round()

matrix([[ 4., 18.,  0.],
        [10., 15.,  8.],
        [14.,  0.,  9.],
        [19.,  0., 20.],
        [ 8.,  5.,  0.],
        [19., 16., 25.]])